SYSTEM:
  NUM_GPUS: 4
  NUM_CPUS: 12
MODEL:
  ARCHITECTURE: "MaskFormer"
  TARGET_OPT: ['9']
  NORM_MODE: sync_bn
  SEM_SEG_HEAD:
    NAME: "MaskFormerHead"
    IGNORE_VALUE: 0 # 255
    NUM_CLASSES: 2
    LOSS_WEIGHT: 1.0
    CONVS_DIM: 128
    MASK_DIM: 16
    NORM: SyncBN # SyncBN
    # pixel decoder
    PIXEL_DECODER_NAME: "MSDeformAttnPixelDecoder"
    IN_FEATURES: ["res2", "res3", "res4", "res5"]
    DEFORMABLE_TRANSFORMER_ENCODER_IN_FEATURES: ["res3", "res4", "res5"]
    COMMON_STRIDE: 4
    TRANSFORMER_ENC_LAYERS: 6
  MASK_FORMER:
    SEMANTIC_LOSS_ON: True
    SEMANTIC_NORM: SyncBN
    SEM_WEIGHT: 5.0
    TRANSFORMER_DECODER_NAME: "MultiScaleMaskedTransformerDecoder"
    TRANSFORMER_IN_FEATURE: "multi_scale_pixel_decoder"
    DEEP_SUPERVISION: True
    NO_OBJECT_WEIGHT: 0.1
    CLASS_WEIGHT: 2.0
    MASK_WEIGHT: 5.0
    DICE_WEIGHT: 5.0
    HIDDEN_DIM: 128
    NUM_OBJECT_QUERIES: 100
    NHEADS: 8
    DROPOUT: 0.0
    DIM_FEEDFORWARD: 1024
    ENC_LAYERS: 0
    PRE_NORM: False
    ENFORCE_INPUT_PROJ: False
    SIZE_DIVISIBILITY: 32
    DEC_LAYERS: 10  # 9 decoder layers, add one for the loss on learnable query
    TRAIN_NUM_POINTS: 12544
    OVERSAMPLE_RATIO: 3.0
    IMPORTANCE_SAMPLE_RATIO: 0.75
    TEST:
      SEMANTIC_ON: False
      INSTANCE_ON: True
      PANOPTIC_ON: False
      OVERLAP_THRESHOLD: 0.8
      OBJECT_MASK_THRESHOLD: 0.8
SOLVER:
  NAME: AdamW
  SAMPLES_PER_BATCH: 2
  LR_SCHEDULER_NAME: WarmupPolyLR # WarmupPolyLR WarmupCosineLR
  BASE_LR: 1e-04 # 0.02
  WARMUP_FACTOR: 0.001 # 1.0
  WARMUP_ITERS: 1000 # 0
  WEIGHT_DECAY: 0.05
  BACKBONE_MULTIPLIER: 0.1
  ITERATION_STEP: 1
  ITERATION_SAVE: 1000 # 100
  START_SAVE: 10000 # 100
  ITERATION_TOTAL: 30000
  ITERATION_VAL: 1000 # 100
  STEPS: (300000,)
DATASET:
  REDUCE_LABEL: True
  PAD_SIZE: [0, 0, 0]
  VAL_PAD_SIZE: [0, 0, 0]
  POST_PROCESS: 'lmc'
  OUTPUT_PATH: outputs/CVPPP_2D_MaskFormer/
INFERENCE:
  OUTPUT_PATH: outputs/CVPPP_2D_MaskFormer/test/
  # OUTPUT_ACT: None



